# Extreme Learning Machine Implementation

No ELM teremos os pesos de entrada dos neurônios definidos de acordo com valores de acordo com uma distribuição gaussiana. A seguir criaremos a função responsável por receber as entradas X, os valores desejados Y e o número de neurônios P. Resultando nos pesos dos neurônios de entrada (U), pesos dos neurônios de saída (V), na predição da rede (Y), na matriz de erro (E) e no erro quadrático médio (EQM).

In [4]:
%matplotlib inline
import numpy as np
#function treinaelm(X, Y, P):
#Valores de Entrada
X = np.array([[0,0],[0,1],[1,0],[1,1]])
D = np.array([0,1,1,1])
P = 10
#X = [0 0;
#     0 1;
#     1 0;
#     1 1];
#D = [0
#     1
#     1
#     1];
# P = 10;

In [10]:
#Gerando valores de U em acordo com uma distribuição gaussiana
U = np.random.randn(P, X.shape[1]+1) #Columns number + 1 because of constants 1    
U6-

array([[ 0.48958809,  1.22940473,  0.27336176],
       [-0.09921529, -0.27819872,  1.3027976 ],
       [ 0.87392171, -0.29441795, -0.78042058],
       [ 0.31159236,  0.23825998,  1.38936066],
       [ 1.24612574,  0.85825306,  0.53323224],
       [ 1.19197366, -0.52687327,  0.28353871],
       [ 1.18778764, -0.67801072, -0.4256908 ],
       [ 0.2862943 ,  0.52532985, -1.47511104],
       [-0.51912772,  2.68212262, -0.10742401],
       [-1.50058849, -1.53892249,  0.10450519]])

In [13]:
Xa = np.c_[X, np.ones([X.shape[0], 1])]
Xa

array([[ 0.,  0.,  1.],
       [ 0.,  1.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1.,  1.]])

In [17]:
M1 = Xa@np.transpose(U) #multiplicação das variáveis Xa com os seus respectivos pesos
M1

array([[ 0.27336176,  1.3027976 , -0.78042058,  1.38936066,  0.53323224,
         0.28353871, -0.4256908 , -1.47511104, -0.10742401,  0.10450519],
       [ 1.50276649,  1.02459888, -1.07483854,  1.62762064,  1.3914853 ,
        -0.24333456, -1.10370151, -0.94978119,  2.57469861, -1.4344173 ],
       [ 0.76294985,  1.20358231,  0.09350113,  1.70095303,  1.77935798,
         1.47551237,  0.76209684, -1.18881674, -0.62655173, -1.39608331],
       [ 1.99235458,  0.92538359, -0.20091683,  1.93921301,  2.63761104,
         0.9486391 ,  0.08408613, -0.66348689,  2.05557089, -2.9350058 ]])

In [18]:
#Função de ativação neurônios de entrada, saída do neurônio de entrada
H = np.tanh(M1)
H

array([[ 0.26675018,  0.86244162, -0.65294804,  0.88303015,  0.48784795,
         0.27617707, -0.40171377, -0.90054797, -0.10701268,  0.1041264 ],
       [ 0.90564693,  0.77173306, -0.79127719,  0.92572199,  0.88349724,
        -0.2386429 , -0.80182468, -0.73968398,  0.98846116, -0.89256828],
       [ 0.6428112 ,  0.83474402,  0.0932296 ,  0.9355281 ,  0.94462606,
         0.9006238 ,  0.64231038, -0.83021153, -0.55567325, -0.8845021 ],
       [ 0.96348343,  0.72843431, -0.19825627,  0.95947155,  0.98981846,
         0.73916632,  0.08388851, -0.58067924,  0.96775044, -0.99437021]])

In [19]:
#Adicionando coluna constantes
Ha = np.c_[H, np.ones([X.shape[0], 1])]
Ha

array([[ 0.26675018,  0.86244162, -0.65294804,  0.88303015,  0.48784795,
         0.27617707, -0.40171377, -0.90054797, -0.10701268,  0.1041264 ,
         1.        ],
       [ 0.90564693,  0.77173306, -0.79127719,  0.92572199,  0.88349724,
        -0.2386429 , -0.80182468, -0.73968398,  0.98846116, -0.89256828,
         1.        ],
       [ 0.6428112 ,  0.83474402,  0.0932296 ,  0.9355281 ,  0.94462606,
         0.9006238 ,  0.64231038, -0.83021153, -0.55567325, -0.8845021 ,
         1.        ],
       [ 0.96348343,  0.72843431, -0.19825627,  0.95947155,  0.98981846,
         0.73916632,  0.08388851, -0.58067924,  0.96775044, -0.99437021,
         1.        ]])

In [20]:
#pesos da entrada dos neurônios de saída
V = np.transpose(np.linalg.pinv(Ha)@D)
V
#     [nl,nc]=size(X);
# M = nc;
# U = randn(P,M+1); % amotragem de distribuicao gaussiana
# Xa = [X ones(nl,1)];
# S = Xa*U';
# H = tanh(S);
# Ha = [H ones(nl,1)];
# Vt = pinv(Ha)*D; % transposta de V
# V = Vt';
# R = Ha*V';
# Y = R;
# E = D-Y;
# [nl,nc]=size(D);
# EQM = 1/(nl*nc)*E(:)'*E(:); %eqm para rede com uma unica saida

array([ 0.3017494 , -0.01046892,  0.10532043,  0.01571073,  0.2853241 ,
       -0.26008485,  0.07988904, -0.01926725, -0.09987388, -0.72023038,
       -0.00488379])

In [21]:
#Multiplicação das saídas dos neurônios de entrada com os pesos das entradas dos neurônios de saída
M2 = Ha@np.transpose(V)
M2

array([  1.38777878e-17,   1.00000000e+00,   1.00000000e+00,
         1.00000000e+00])

In [22]:
#Gerando os valores da predição, como a função é Y(x)=x temos que Y = M2
Y= M2

In [23]:
#Calculando a matriz de erro na saída de cada neurônio de saída
E = D-Y
E

array([ -1.38777878e-17,   0.00000000e+00,  -2.22044605e-16,
        -6.66133815e-16])

In [46]:
#Erro Quadrático Médio
EQM= 1/(np.array([D]).shape[0]*np.array([D]).shape[1]*(E@np.transpose(E)))
EQM

5.0686224702604723e+29