# Classificadores

In [1]:
%matplotlib inline
import numpy as np
from sklearn.utils import shuffle

def treinaelmclass(X,D,P):
    U = np.random.randn(P, X.shape[1]+1) #Distribuição Gaussiana
    Xa = np.c_[X, np.ones(X.shape[0])]
    S = Xa@np.transpose(U)
    H = np.tanh(S)
    Ha = np.c_[H,np.ones(X.shape[0])]
    V = np.transpose(np.linalg.pinv(Ha)@D)
    R = Ha@np.transpose(V)
    Y = R
    E = D-Y
    EQM = 1/(D.shape[0]*D.shape[1])*(np.transpose(E)@E)  #EQM da rede
    taxa = 100* np.sum(np.equal(np.amax(Y, axis=0),np.amax(D, axis=0)))
    return (U,V,Y,E,EQM,taxa)

In [2]:
def erroelmclass(X,D,U,V):
    Xa = np.c_[X,np.ones(X.shape[0])]
    S = Xa@np.transpose(U)
    H = np.tanh(S)
    Ha = np.c_[H,np.ones(X.shape[0])]
    R = Ha@np.transpose(V)
    Y = R
    E = D-Y
    EQM = 1/(D.shape[0]*D.shape[1])*(np.transpose(E)@E)
    taxa = 100* np.sum(np.equal(np.amax(Y, axis=0),np.amax(D, axis=0)))
    return (Y,E,EQM,taxa)

In [3]:
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
D = np.array([[1,0],[0,1],[0,1],[1,0],[0,1],[1,0],[1,0],[0,1]])
display(X,X.shape,D,D.shape)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

(8, 3)

array([[1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1]])

(8, 2)

In [4]:
X, D= shuffle(X, D, random_state=0)
display(X,D)

array([[1, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 0]])

array([[1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1]])

In [5]:
numtr = int(np.ceil(0.7*X.shape[0]))
Xtr = X[0:numtr,:]
Dtr = D[0:numtr,:]
Xt = X[numtr:,:]
Dt = D[numtr:,:]
display(Xtr,Dtr,Xt,Dt)

array([[1, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 0]])

array([[1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0]])

array([[1, 0, 1],
       [1, 0, 0]])

array([[1, 0],
       [0, 1]])

In [6]:
Xtrmin = np.amin(Xtr, axis=0)
Xtrmax = np.amax(Xtr, axis=0)

Xtremin = np.ones((1,X.shape[1]))*-1
Xtremax = np.ones((1,X.shape[1]))

display(Xtrmin, Xtrmax, Xtremin, Xtremax)

array([0, 0, 0])

array([1, 1, 1])

array([[-1., -1., -1.]])

array([[ 1.,  1.,  1.]])

In [7]:
Xtre = ((Xtremax-Xtremin)*(Xtr - Xtrmin))/(Xtrmax-Xtrmin)+Xtremin
Dtre = Dtr
P = 5
display(Xtre)

array([[ 1.,  1., -1.],
       [-1.,  1., -1.],
       [-1., -1.,  1.],
       [ 1.,  1.,  1.],
       [-1.,  1.,  1.],
       [-1., -1., -1.]])

In [8]:
[U,V,Ytre,Etre,EQMtre,taxatre] = treinaelmclass(Xtre,Dtre,P)
Xte = (Xtremax-Xtremin)*(Xt-Xtrmin)/(Xtrmax-Xtrmin)+Xtremin
Dte = Dt
[Yte,Ete,EQMte,taxate] = erroelmclass(Xte,Dte,U,V)
display(taxatre, taxate)

0

0