# Classificadores

In [12]:
%matplotlib inline
import numpy as np
from sklearn.utils import shuffle

def treinaelmclass(X,D,P):
    U = np.random.randn(P, X.shape[1]) #Distribuição Gaussiana
    Xa = np.c_[X, np.ones(X.shape[0])]
    S = Xa@np.transpose(U)
    H = np.tanh(S)
    Ha = np.c_[H,np.ones(X.shape[0])]
    V = np.transpose(np.linalg.pinv(Ha)@D)
    R = Ha@np.transpose(V)
    Y = R
    E = D-Y
    EQM = 1/(D.shape[0]*D.shape[1])*(np.transpose(E)@E)  #EQM da rede
    taxa = 100* np.sum(np.equal(np.amax(Y, axis=0),np.amax(D, axis=0)))
    return (U,V,Y,E,EQM,taxa)

In [13]:
def erroelm(X,D,U,V):
    Xa = np.c_[X,np.ones(X.shape[0])]
    S = Xa@np.transpose(U)
    H = np.tanh(S)
    Ha = np.c_[H,np.ones(X.shape[0])]
    R = Ha@np.transpose(V)
    Y = R
    E = D-Y
    EQM = 1/(D.shape[0]*D.shape[1])*(np.transpose(E)@E)
    taxa = 100* np.sum(np.equal(np.amax(Y, axis=0),np.amax(D, axis=0)))
    return (Y,E,EQM,taxa)

In [14]:
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
D = np.array([[1,0],[0,1],[0,1],[1,0],[0,1],[1,0],[1,0],[0,1]])
display(X,X.shape,D,D.shape)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

(8, 3)

array([[1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1]])

(8, 2)

In [15]:
X, D= shuffle(X, D, random_state=0)
display(X,D)

array([[1, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 0],
       [1, 0, 1],
       [1, 0, 0]])

array([[1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1]])

In [22]:
numtr = int(np.ceil(0.7*X.shape[0]))
Xtr = X[0:numtr,:]
Dtr = D[0:numtr,:]
Xt = X[numtr:,:]
Dt = D[numtr:,:]
display(Xtr,Dtr,Xt,Dt)

6

array([[1, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 0]])

array([[1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0]])

array([[1, 0, 1],
       [1, 0, 0]])

array([[1, 0],
       [0, 1]])

In [20]:
# xtrmin = min(Xtr); %maximo em cada coluna
# xtrmax = max(Xtr);
# xtremin = -1*ones(1,nc);
# xtremax = 1*ones(1,nc);
# [nl,nc] = size(Xtr); % nl � o total de padr�es
# Xtre = repmat((xtremax-xtremin),nl,1).*(Xtr-repmat(xtrmin,nl,1))./repmat((xtrmax-xtrmin),nl,1)+repmat(xtremin,nl,1);
# Dtre = Dtr;
# P = 5;
# %introducao do escalonamento
# [U,V,Ytre,Etre,EQMtre,taxatre] = treinaelmclass(Xtre,Dtre,P);
# % escalonando exemplos do conjunto de teste
# % Xte = (xtremax-xtremin)*(Xt-xtrmin)/(xtrmax-xtrmin)+xtremin;
# [nl,nc] = size(Xt); % nl � o total de padr�es
# Xte = repmat((xtremax-xtremin),nl,1).*(Xt-repmat(xtrmin,nl,1))./repmat((xtrmax-xtrmin),nl,1)+repmat(xtremin,nl,1);
# % conversao de Dt para que os erros sejam calculados na escala em que
# % o treinamento foi realizado
# Dte = Dt;
# % calculo da saida da rede para o conjunto de teste
# [Yte,Ete,EQMte,taxate] = erroelmclass(Xte,Dte,U,V);