# Classificadores

In [1]:
%matplotlib inline
import numpy as np
from sklearn.utils import shuffle

#Setando um valor para a seed para não variar os valores randômicos e assim testar melhor o código
#np.random.seed(0)

def treinaelmclass(X,D,P):
    U = np.random.randn(P, X.shape[1]+1) #Distribuição Gaussiana
    Xa = np.c_[X, np.ones(X.shape[0])]
    S = Xa@np.transpose(U)
    H = np.tanh(S)
    Ha = np.c_[H,np.ones(X.shape[0])]
    V = np.transpose(np.linalg.pinv(Ha)@D)
    R = Ha@np.transpose(V)
    Y = R
    E = D-Y
    EQM = 1/(D.shape[0]*D.shape[1])*(np.transpose(E)@E)  #EQM da rede
    taxa = 100* np.sum(np.equal(np.argmax(Y, axis=1),np.argmax(D, axis=1)))/X.shape[0]
    return (U,V,Y,E,EQM,taxa)

In [2]:
def erroelmclass(X,D,U,V):
    Xa = np.c_[X,np.ones(X.shape[0])]
    S = Xa@np.transpose(U)
    H = np.tanh(S)
    Ha = np.c_[H,np.ones(X.shape[0])]
    R = Ha@np.transpose(V)
    Y = R
    E = D-Y
    EQM = 1/(D.shape[0]*D.shape[1])*(np.transpose(E)@E)
    taxa = 100* np.sum(np.equal(np.argmax(Y, axis=1),np.argmax(D, axis=1)))/X.shape[0]
    return (Y,E,EQM,taxa)

In [3]:
winedata = np.loadtxt('./datasets/wine/wine.data',delimiter=',') #Lendo os valores do dataset
X = np.delete(winedata, 0,1) #Deletando a primeira coluna da matriz, pois a primeira coluna será o valor de D
Da = np.round(winedata[:,0]).astype(int) #Pegando os valores da primeira coluna que correspondem a classificação dos vinhos
D = np.zeros((winedata.shape[0],3))
for i in range(0,len(Da)): #Preenchendo os valores de D de acordo com o formato de classificação, se o valor do primeiro elemento é 3 então criará um subarray como [0,0,1] e adicionará no array D, para seguir a convençao de classificação adotada que é algo como [[0,0,1],[1,0,0],[0,1,0]] que corresponderia a [3,1,2]
    D[i,Da[i]-1] = 1
    
display(X.shape, D.shape)

array([[  1.42300000e+01,   1.71000000e+00,   2.43000000e+00, ...,
          1.04000000e+00,   3.92000000e+00,   1.06500000e+03],
       [  1.32000000e+01,   1.78000000e+00,   2.14000000e+00, ...,
          1.05000000e+00,   3.40000000e+00,   1.05000000e+03],
       [  1.31600000e+01,   2.36000000e+00,   2.67000000e+00, ...,
          1.03000000e+00,   3.17000000e+00,   1.18500000e+03],
       ..., 
       [  1.32700000e+01,   4.28000000e+00,   2.26000000e+00, ...,
          5.90000000e-01,   1.56000000e+00,   8.35000000e+02],
       [  1.31700000e+01,   2.59000000e+00,   2.37000000e+00, ...,
          6.00000000e-01,   1.62000000e+00,   8.40000000e+02],
       [  1.41300000e+01,   4.10000000e+00,   2.74000000e+00, ...,
          6.10000000e-01,   1.60000000e+00,   5.60000000e+02]])

In [4]:
X, D= shuffle(X, D, random_state=0)
display(X,D)

array([[  1.37400000e+01,   1.67000000e+00,   2.25000000e+00, ...,
          9.20000000e-01,   3.20000000e+00,   1.06000000e+03],
       [  1.27900000e+01,   2.67000000e+00,   2.48000000e+00, ...,
          4.80000000e-01,   1.47000000e+00,   4.80000000e+02],
       [  1.23700000e+01,   1.13000000e+00,   2.16000000e+00, ...,
          1.22000000e+00,   2.87000000e+00,   4.20000000e+02],
       ..., 
       [  1.24200000e+01,   1.61000000e+00,   2.19000000e+00, ...,
          1.06000000e+00,   2.96000000e+00,   3.45000000e+02],
       [  1.39000000e+01,   1.68000000e+00,   2.12000000e+00, ...,
          9.10000000e-01,   3.33000000e+00,   9.85000000e+02],
       [  1.41600000e+01,   2.51000000e+00,   2.48000000e+00, ...,
          6.20000000e-01,   1.71000000e+00,   6.60000000e+02]])

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

In [5]:
numtr = int(np.ceil(0.7*X.shape[0]))
Xtr = X[0:numtr,:]
Dtr = D[0:numtr,:]
Xt = X[numtr:,:]
Dt = D[numtr:,:]
display(Xtr,Dtr,Xt,Dt)

array([[  1.37400000e+01,   1.67000000e+00,   2.25000000e+00, ...,
          9.20000000e-01,   3.20000000e+00,   1.06000000e+03],
       [  1.27900000e+01,   2.67000000e+00,   2.48000000e+00, ...,
          4.80000000e-01,   1.47000000e+00,   4.80000000e+02],
       [  1.23700000e+01,   1.13000000e+00,   2.16000000e+00, ...,
          1.22000000e+00,   2.87000000e+00,   4.20000000e+02],
       ..., 
       [  1.34800000e+01,   1.81000000e+00,   2.41000000e+00, ...,
          1.04000000e+00,   3.47000000e+00,   9.20000000e+02],
       [  1.32900000e+01,   1.97000000e+00,   2.68000000e+00, ...,
          1.07000000e+00,   2.84000000e+00,   1.27000000e+03],
       [  1.34100000e+01,   3.84000000e+00,   2.12000000e+00, ...,
          9.10000000e-01,   3.00000000e+00,   1.03500000e+03]])

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

array([[  1.37100000e+01,   5.65000000e+00,   2.45000000e+00,
          2.05000000e+01,   9.50000000e+01,   1.68000000e+00,
          6.10000000e-01,   5.20000000e-01,   1.06000000e+00,
          7.70000000e+00,   6.40000000e-01,   1.74000000e+00,
          7.40000000e+02],
       [  1.23700000e+01,   1.21000000e+00,   2.56000000e+00,
          1.81000000e+01,   9.80000000e+01,   2.42000000e+00,
          2.65000000e+00,   3.70000000e-01,   2.08000000e+00,
          4.60000000e+00,   1.19000000e+00,   2.30000000e+00,
          6.78000000e+02],
       [  1.32000000e+01,   1.78000000e+00,   2.14000000e+00,
          1.12000000e+01,   1.00000000e+02,   2.65000000e+00,
          2.76000000e+00,   2.60000000e-01,   1.28000000e+00,
          4.38000000e+00,   1.05000000e+00,   3.40000000e+00,
          1.05000000e+03],
       [  1.14500000e+01,   2.40000000e+00,   2.42000000e+00,
          2.00000000e+01,   9.60000000e+01,   2.90000000e+00,
          2.79000000e+00,   3.20000000e-01,   1.830

array([[ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.

In [6]:
Xtrmin = np.amin(Xtr, axis=0)
Xtrmax = np.amax(Xtr, axis=0)

Xtremin = np.ones((1,X.shape[1]))*-1
Xtremax = np.ones((1,X.shape[1]))

display(Xtrmin, Xtrmax, Xtremin, Xtremax)

array([  1.14100000e+01,   7.40000000e-01,   1.36000000e+00,
         1.06000000e+01,   7.00000000e+01,   9.80000000e-01,
         3.40000000e-01,   1.30000000e-01,   4.10000000e-01,
         1.28000000e+00,   4.80000000e-01,   1.27000000e+00,
         2.78000000e+02])

array([  1.48300000e+01,   5.80000000e+00,   3.23000000e+00,
         3.00000000e+01,   1.62000000e+02,   3.88000000e+00,
         5.08000000e+00,   6.30000000e-01,   3.58000000e+00,
         1.30000000e+01,   1.45000000e+00,   4.00000000e+00,
         1.68000000e+03])

array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [7]:
Xtre = ((Xtremax-Xtremin)*(Xtr - Xtrmin))/(Xtrmax-Xtrmin)+Xtremin
Dtre = Dtr
P = 5
display(Xtre)

array([[ 0.3625731 , -0.63241107, -0.04812834, ..., -0.09278351,
         0.41391941,  0.11554922],
       [-0.19298246, -0.23715415,  0.19786096, ..., -1.        ,
        -0.85347985, -0.71184023],
       [-0.43859649, -0.8458498 , -0.14438503, ...,  0.5257732 ,
         0.17216117, -0.79743224],
       ..., 
       [ 0.21052632, -0.5770751 ,  0.12299465, ...,  0.15463918,
         0.61172161, -0.08416548],
       [ 0.0994152 , -0.51383399,  0.41176471, ...,  0.21649485,
         0.15018315,  0.41512126],
       [ 0.16959064,  0.22529644, -0.18716578, ..., -0.11340206,
         0.26739927,  0.07988588]])

In [8]:
[U,V,Ytre,Etre,EQMtre,taxatre] = treinaelmclass(Xtre,Dtre,P)
Xte = (Xtremax-Xtremin)*(Xt-Xtrmin)/(Xtrmax-Xtrmin)+Xtremin
Dte = Dt
[Yte,Ete,EQMte,taxate] = erroelmclass(Xte,Dte,U,V)
display(taxatre, taxate)

92.0

86.79245283018868