## Parametrização escolhida y(x) = 

In [1]:
%matplotlib inline
import numpy as np
X = np.array([1,1.5,2,2.5,3,3.5,4])
X

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [2]:
Xb = np.c_[np.sin(X - np.pi).transpose()*(X.transpose()**2), np.sin(X - np.pi)*X, np.ones(X.shape)]
Xb

array([[ -0.84147098,  -0.84147098,   1.        ],
       [ -2.24436372,  -1.49624248,   1.        ],
       [ -3.63718971,  -1.81859485,   1.        ],
       [ -3.7404509 ,  -1.49618036,   1.        ],
       [ -1.27008007,  -0.42336002,   1.        ],
       [  4.29709454,   1.2277413 ,   1.        ],
       [ 12.10883992,   3.02720998,   1.        ]])

In [3]:
d = np.array([2.5,5,8.5,13,18.5,25,29.32]).transpose()
d

array([  2.5 ,   5.  ,   8.5 ,  13.  ,  18.5 ,  25.  ,  29.32])

In [4]:
teta = np.linalg.pinv(Xb)@d
teta

array([ -3.21961164,  15.19199397,  20.64661554])

In [5]:
Y = Xb@teta
Y

array([ 10.57220319,   5.14168836,   4.7288718 ,   9.95945178,
        18.30409719,  25.46347833,  27.65020937])

In [6]:
error = d-Y
error

array([-8.07220319, -0.14168836,  3.7711282 ,  3.04054822,  0.19590281,
       -0.46347833,  1.66979063])

In [7]:
eqm = np.sum(np.power(error,2))
eqm

91.688272086976497

In [8]:
rmse = np.sqrt(eqm)
rmse

9.5753993173640808